modLoader = "javafml"
loaderVersion = "[38,)"
issueTrackerURL = "https://github.com/PssbleTrngle/Brazier/issues"
license = "https://github.com/PssbleTrngle/Brazier/blob/master/LICENSE.txt"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/brazier"

[[mods]]
    modId = "brazier"
    version = "${version}"
    displayName = "Brazier"
    authors = "possible_triangle"
    description = '''Prevent mob spawning with a beacon-like structure'''

[[dependencies.brazier]]
    modId = "forge"
    mandatory = true
    versionRange = "[39.1.0,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.18.1,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "architectury"
    mandatory = true
    versionRange = "[3.7.26,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "cloth-config"
    mandatory = true
    versionRange = "[6.2.57,)"
    ordering = "NONE"
    side = "BOTH"