modLoader = "javafml"
loaderVersion = "[41,)"
issueTrackerURL = "https://github.com/PssbleTrngle/Brazier/issues"
license = "https://github.com/PssbleTrngle/Brazier/blob/master/LICENSE.txt"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/brazier"
showAsResourcePack = false

[[mods]]
    modId = "brazier"
    version = "${version}"
    displayName = "Brazier"
    authors = "possible_triangle"
    description = '''Prevent mob spawning with a beacon-like structure'''

[[dependencies.brazier]]
    modId = "forge"
    mandatory = true
    versionRange = "[41,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "architectury"
    mandatory = true
    versionRange = "[6.0.37,)"
    ordering = "AFTER"
    side = "BOTH"
[[dependencies.brazier]]
    modId = "cloth_config"
    mandatory = true
    versionRange = "[8.0.75,)"
    ordering = "NONE"
    side = "BOTH"