modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/PssbleTrngle/Brazier/issues"
license="https://github.com/PssbleTrngle/Brazier/blob/master/LICENSE.txt"

[[mods]]
    modId="brazier"
    version="${file.jarVersion}"
    displayName="Brazier"
    authors="possible_triangle"
    description='''Prevent mob spawning with a beacon-like structure'''

[[dependencies.brazier]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brazier]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
