modLoader="javafml"
loaderVersion="[32,)"
#issueTrackerURL="http://my.issue.tracker/"
[[mods]]
modId="brazier"
version="${file.jarVersion}"
displayName="Brazier"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
#logoFile="examplemod.png"
#credits="Me hehe"
#authors="possible_triangle"
description='''
Prevent mob spawning with a beacon-like structure
'''

[[dependencies.divide]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.divide]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
