modLoader="javafml"
loaderVersion="[34,)"
issueTrackerURL="https://github.com/PssbleTrngle/Brazier/issues"
license="https://github.com/PssbleTrngle/Brazier/blob/master/LICENSE.txt"
displayURL="https://www.curseforge.com/minecraft/mc-mods/brazier"

[[mods]]
    modId="brazier"
    version="${file.jarVersion}"
    displayName="Brazier"
    authors="possible_triangle"
    description='''Prevent mob spawning with a beacon-like structure'''

[[dependencies.brazier]]
    modId="forge"
    mandatory=true
    versionRange="[34.0.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.brazier]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"
