name: Build Forge

on:
  release:
    types: [created]

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get release
        id: release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'gradle.properties'
          property: 'mod_version'
          value: ${{ steps.release.outputs.tag_name }}

      - name: Build Mod
        run: chmod +x ./gradlew && ./gradlew forge:build

      - name: Upload to Release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: forge/build/libs/brazier-${{ steps.release.outputs.tag_name }}-forge.jar
          asset_name: brazier-forge.jar
          asset_content_type: application/java-archive

      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 402616
          game_endpoint: minecraft
          file_path: forge/build/libs/brazier-${{ steps.release.outputs.tag_name }}-forge.jar
          changelog: ${{ steps.release.outputs.body }}
          changelog_type: markdown
          display_name: Version ${{ steps.release.outputs.tag_name }}
          game_versions: 8203,8134,8056,7498
          release_type: release
          relations: architectury-forge:requiredDependency,cloth-config-forge:requiredDependency,jei:optionalDependency
