name: Release

on:
  pull_request:
    types: [ closed ]
    branches: [ master ]
  repository_dispatch:
    types: [ release-mod ]

jobs:

  publish:
    if: github.event_name != 'pull_request' || (github.event.pull_request.merged && contains(github.event.pull_request.labels.*.name, 'release'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - uses: PssbleTrngle/VersionManagment@v1.0.4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
        id: version
          
      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: 'build.properties'
          property: 'mod_version'
          value: ${{ steps.version.outputs.next }} 
        
      - name: Build Mod
        run: chmod +x ./gradlew && ./gradlew build
      
      - name: Update Changelog
        uses: vemel/update-changelog@0.0.1
        id: changelog
        with:
          version: ${{ steps.version.outputs.next }}
        
      - name: Create Release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.next }}
          release_name: Release ${{ steps.version.outputs.next }}
          body: ${{ steps.changelog.outputs.pulls_list_md }}
  
      - name: Upload Mod Jar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }}
          asset_path: build/libs/Brazier-${{ steps.version.outputs.next }}.jar
          asset_name: brazier.jar
          asset_content_type: application/java-archive
         
      - name: Upload to CurseForge
        uses: itsmeow/curseforge-upload@master
        with:
          token: ${{ secrets.CURSEFORGE_TOKEN }}
          project_id: 402616
          game_endpoint: minecraft
          file_path: build/libs/Brazier-${{ steps.version.outputs.next }}.jar
          changelog: ${{ steps.changelog.outputs.pulls_list_md }}
          changelog_type: markdown  
          display_name: Version ${{ steps.version.outputs.next }}
          game_versions: 7892,4458,7498
          release_type: beta

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_message: Update Changelog
          branch: master
          repository: .
          commit_user_name: PssbleTrngle
          commit_user_email: nik@somethingcatchy.net
          commit_author: PssbleTrngle <nik@somethingcatchy.net>
