on:
  workflow_call:
    inputs:
      cache:
        required: true
        default: true
        type: boolean
        description: 'Should gradle packages be cached'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache Gradle packages
        if: ${{ inputs.cache }}
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x ./gradlew