name: Build & Analyze
on:
  push:
    branches: [ 1.18.x ]

jobs:

  setup:
    uses: PssbleTrngle/Brazier/.github/workflows/setup.yml@1.18.x
    with:
      cache: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.cache }}

  build:
    name: Analyze
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: PssbleTrngle/Brazier/.github/workflows/setup.yml@1.18.x

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonarqube
